# Change these first
owner: teasyastron # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.astron.live
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Status Page** for teasyastron"
  introMessage: Real-time status for our services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
